apiVersion: 1

prune: true

datasources:
  - name: Finite Prometheus
    type: prometheus
    uid: finite-prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      httpMethod: POST
      prometheusType: Prometheus
      prometheusVersion: 3.13.2
      timeInterval: 1m

