//! Ordered schema migrations and explicit rollback/remap scripts.

pub const CORE_SCHEMA_SQL: &str = concat!(
    include_str!("../migrations/0001_core.sql"),
    "\n",
    include_str!("../migrations/0002_runtime_upgrade.sql"),
    "\n",
    include_str!("../migrations/0003_launch_codes.sql"),
    "\n",
    include_str!("../migrations/0004_membership_archive.sql"),
    "\n",
    include_str!("../migrations/0005_phala_expand.sql"),
    "\n",
    include_str!("../migrations/0006_runtime_capabilities_expand.sql"),
    "\n",
    include_str!("../migrations/0007_provider_creation_operations.sql"),
    "\n",
    include_str!("../migrations/0008_agent_creation_provisional_runtime.sql"),
    "\n",
    include_str!("../migrations/0009_artifact_recovery_support.sql"),
    "\n",
    include_str!("../migrations/0010_align_finite_private_generous.sql"),
    "\n",
    include_str!("../migrations/0011_agent_email.sql"),
    "\n",
    include_str!("../migrations/0012_runtime_retirement_snapshots.sql"),
    "\n",
    include_str!("../migrations/0013_double_finite_private_default.sql"),
    "\n",
    include_str!("../migrations/0014_finite_private_user_controls.sql"),
    "\n",
    include_str!("../migrations/0015_runner_capacity_fences.sql"),
    "\n",
    include_str!("../migrations/0016_runtime_cold_relocation.sql"),
    "\n",
    include_str!("../migrations/0017_rfc3339_reads.sql"),
    "\n",
    include_str!("../migrations/0018_finite_private_5x_profile.sql"),
    "\n",
    include_str!("../migrations/0019_brain_agent_departure_facts.sql"),
    "\n",
    include_str!("../migrations/0020_runtime_offboarding_phases.sql"),
    "\n",
    include_str!("../migrations/0021_runtime_lifecycle.sql"),
    "\n",
    include_str!("../migrations/0022_runtime_health_reports.sql"),
    "\n",
    include_str!("../migrations/0023_agent_creation_owner_chat_account_id.sql"),
    "\n",
    include_str!("../migrations/0024_runtime_status_pending_first_report_remap.sql"),
    "\n",
    include_str!("../migrations/0025_account_email_changes.sql"),
    "\n",
    include_str!("../migrations/0026_launch_code_host_targets.sql"),
    "\n",
    include_str!("../migrations/0027_launch_code_target_retry.sql"),
    "\n",
    include_str!("../migrations/0028_launch_code_cohort_targets.sql"),
    "\n",
    include_str!("../migrations/0029_launch_host_reservation_releases.sql"),
    "\n",
    include_str!("../migrations/0030_runtime_hosted_hermes.sql")
);

pub const RUNTIME_UPGRADE_ROLLBACK_RESCUE_SQL: &str =
    include_str!("../migrations/runtime_upgrade_rollback_rescue.sql");

pub const RUNTIME_LIFECYCLE_REVERSE_REMAP_SQL: &str =
    include_str!("../migrations/runtime_lifecycle_reverse_remap.sql");
