name: check

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  static:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run static checks
        run: scripts/check-static.sh

