export const TYPE_SCALE = [
  {
    name: "Display",
    className: "type-display",
    size: "32px / 2rem",
    lineHeight: "1.1",
    weight: "600",
    tracking: "0",
    use: "Rare marketing hero",
  },
  {
    name: "Title 1",
    className: "type-title-1",
    size: "28px -> 32px (md)",
    lineHeight: "1.15",
    weight: "600",
    tracking: "0",
    use: "Page titles",
  },
  {
    name: "Title 2",
    className: "type-title-2",
    size: "22px / 1.375rem",
    lineHeight: "1.2",
    weight: "600",
    tracking: "0",
    use: "Section headings",
  },
  {
    name: "Title 3",
    className: "type-title-3",
    size: "18px / 1.125rem",
    lineHeight: "1.25",
    weight: "600",
    tracking: "0",
    use: "Card, dialog, sheet titles",
  },
  {
    name: "Body lg",
    className: "type-body-lg",
    size: "15px / 0.9375rem",
    lineHeight: "1.45",
    weight: "400",
    tracking: "0",
    use: "Lead copy, descriptions",
  },
  {
    name: "Body",
    className: "type-body",
    size: "14px / 0.875rem",
    lineHeight: "1.45",
    weight: "400",
    tracking: "0",
    use: "Default UI",
  },
  {
    name: "Body sm",
    className: "type-body-sm",
    size: "13px / 0.8125rem",
    lineHeight: "1.4",
    weight: "400",
    tracking: "0",
    use: "Secondary UI copy",
  },
  {
    name: "Caption",
    className: "type-caption",
    size: "12px / 0.75rem",
    lineHeight: "1.35",
    weight: "500",
    tracking: "0",
    use: "Metadata, helper text",
  },
  {
    name: "Label",
    className: "type-label",
    size: "11px / 0.6875rem",
    lineHeight: "1.2",
    weight: "600",
    tracking: "0",
    use: "Eyebrows, uppercase labels",
  },
  {
    name: "Mono",
    className: "type-mono",
    size: "13px / 0.8125rem",
    lineHeight: "1.45",
    weight: "400",
    tracking: "0",
    use: "Inline code, IDs",
  },
  {
    name: "Mono sm",
    className: "type-mono-sm",
    size: "12px / 0.75rem",
    lineHeight: "1.4",
    weight: "400",
    tracking: "0",
    use: "Compact code, token swatches",
  },
] as const;
